apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.group: serverless    
spec:
  destination:
    namespace: knative-serving
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/instances/knative-serving
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
